export const FETCH_DELETE_COMMENT_REQUEST = "FETCH_DELETE_COMMENT_REQUEST";
export const FETCH_DELETE_COMMENT_SUCCESS = "FETCH_DELETE_COMMENT_SUCCESS";
export const FETCH_DELETE_COMMENT_FAILURE = "FETCH_DELETE_COMMENT_FAILURE";